# https://golangci-lint.run/usage/linters/
linters:
  enable-all: true
  disable:
    # not useful
    - exhaustivestruct
    - exhaustruct

linters-settings:
  gci:
    local-prefixes: github.com/dijiujun/boss_apu_exporter
  goimports:
    local-prefixes: github.com/dijiujun/boss_apu_exporter
  goconst:
    ignore-tests: true
  gomoddirectives:
    replace-allow-list:
      - gopkg.in/alecthomas/kingpin.v2
