{
 "title": "BlueOcean APU Metrics",
 "description": "BlueOcean APU Metrics based on the prometheus metrics from github.com/dijiujun/boss_apu_exporter",
 "tags": [
  "prometheus",
  "blueocean",
  "boss_apu_exporter",
  "boss-smi"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "this_job",
    "label": "job",
    "query": {
     "query": "label_values(boss_smi_gpu_info, job)"
    }
   },
   {
    "name": "this_instance",
    "label": "ip",
    "query": {
     "query": "label_values(boss_smi_gpu_info{job=~\"$this_job\"},instance)"
    }
   },
   {
    "name": "this_cardid",
    "label": "card",
    "query": {
     "query": "label_values(boss_smi_gpu_info{job=~\"$this_job\",instance=~\"$this_instance\"},card_index)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Name",
   "type": "stat",
   "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Chip Type",
   "type": "stat",
   "description": "The chip type of the card",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "prefix:P" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{chip_type}}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "gauge",
   "description": "The last measured power draw for the entire board, in watts.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_pwr{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}"
    }
   ]
  },
  {
   "title": "Card Temperature",
   "type": "gauge",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_card_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Inlet Temperature",
   "type": "gauge",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_inlet_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Outlet Temperature",
   "type": "gauge",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_outlet_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die0 Temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_die0_bxlink_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "bxlink"
    },
    {
     "expr": "boss_smi_die0_gpgpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "gpgpu"
    },
    {
     "expr": "boss_smi_die0_cpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "cpu"
    },
    {
     "expr": "boss_smi_die0_ddr_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "ddr"
    },
    {
     "expr": "boss_smi_die0_decoder_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "decoder"
    },
    {
     "expr": "boss_smi_die0_sys_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Bus ID",
   "type": "stat",
   "description": "The version of the installed NVIDIA display driver. This is an alphanumeric string.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{bus_id}}"
    }
   ]
  },
  {
   "title": "Link Width",
   "type": "stat",
   "description": "The width of pcie link",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_link_width{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}"
    }
   ]
  },
  {
   "title": "Board ID",
   "type": "stat",
   "description": "The id of board",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{board_id}}"
    }
   ]
  },
  {
   "title": "CPLD Version",
   "type": "stat",
   "description": "The version of CPLD",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_cpld_version{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}"
    }
   ]
  },
  {
   "title": "Die0 Utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_die0_cpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "boss_smi_die0_gpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "GPU使用率"
    },
    {
     "expr": "(boss_smi_die0_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"} / boss_smi_die0_mem_total{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"})* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(boss_smi_die0_gpu_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"} / boss_smi_die0_gpu_mem_total{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"})* 100",
     "legendFormat": "GPU显存使用率"
    }
   ]
  },
  {
   "title": "Die1 Utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_die1_cpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "boss_smi_die1_gpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "GPU使用率"
    },
    {
     "expr": "(boss_smi_die1_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"} / boss_smi_die1_mem_total{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"})* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(boss_smi_die1_gpu_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"} / boss_smi_die1_gpu_mem_total{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"})* 100",
     "legendFormat": "GPU显存使用率"
    }
   ]
  },
  {
   "title": "Die1 Temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_die1_bxlink_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "bxlink"
    },
    {
     "expr": "boss_smi_die1_gpgpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "gpgpu"
    },
    {
     "expr": "boss_smi_die1_cpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "cpu"
    },
    {
     "expr": "boss_smi_die1_ddr_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "ddr"
    },
    {
     "expr": "boss_smi_die1_decoder_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "decoder"
    },
    {
     "expr": "boss_smi_die1_sys_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Soft Version",
   "type": "stat",
   "description": "The version of the installed NVIDIA display driver. This is an alphanumeric string.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{soft_version}}"
    }
   ]
  },
  {
   "title": "APU Version",
   "type": "stat",
   "description": "The BIOS of the GPU board.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{apu_version}}"
    }
   ]
  },
  {
   "title": "Die2 Utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_die2_cpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "boss_smi_die2_gpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "GPU使用率"
    },
    {
     "expr": "(boss_smi_die2_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"} / boss_smi_die2_mem_total{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"})* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(boss_smi_die2_gpu_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"} / boss_smi_die2_gpu_mem_total{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"})* 100",
     "legendFormat": "GPU显存使用率"
    }
   ]
  },
  {
   "title": "Die3 Utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_die3_cpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "boss_smi_die3_gpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "GPU使用率"
    },
    {
     "expr": "(boss_smi_die3_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"} / boss_smi_die3_mem_total{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"})* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(boss_smi_die3_gpu_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"} / boss_smi_die3_gpu_mem_total{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"})* 100",
     "legendFormat": "GPU显存使用率"
    }
   ]
  },
  {
   "title": "Die2 Temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_die2_bxlink_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "bxlink"
    },
    {
     "expr": "boss_smi_die2_gpgpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "gpgpu"
    },
    {
     "expr": "boss_smi_die2_cpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "cpu"
    },
    {
     "expr": "boss_smi_die2_ddr_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "ddr"
    },
    {
     "expr": "boss_smi_die2_decoder_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "decoder"
    },
    {
     "expr": "boss_smi_die2_sys_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Die0 SN",
   "type": "stat",
   "description": "The BIOS of the GPU board.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{die0_sn}}"
    }
   ]
  },
  {
   "title": "Die1 SN",
   "type": "stat",
   "description": "serial no. of each die",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{die1_sn}}"
    }
   ]
  },
  {
   "title": "Die2 SN",
   "type": "stat",
   "description": "serial no. of each die",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{die2_sn}}"
    }
   ]
  },
  {
   "title": "Die3 SN",
   "type": "stat",
   "description": "serial no. of each die",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{die3_sn}}"
    }
   ]
  },
  {
   "title": "Phy Memory",
   "type": "bargauge",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boss_smi_die0_phy_mem{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Die0"
    },
    {
     "expr": "boss_smi_die1_phy_mem{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Die1"
    },
    {
     "expr": "boss_smi_die2_phy_mem{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Die2"
    },
    {
     "expr": "boss_smi_die3_phy_mem{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Die3"
    }
   ]
  },
  {
   "title": "Die0 Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boss_smi_die0_cpu_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "CPU"
    },
    {
     "expr": "boss_smi_die0_gpu_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "GPU"
    },
    {
     "expr": "boss_smi_die0_ddr_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "DDR"
    }
   ]
  },
  {
   "title": "Die1 Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boss_smi_die1_cpu_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "CPU"
    },
    {
     "expr": "boss_smi_die1_gpu_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "GPU"
    },
    {
     "expr": "boss_smi_die1_ddr_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "DDR"
    }
   ]
  },
  {
   "title": "Die2 Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boss_smi_die2_cpu_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "CPU"
    },
    {
     "expr": "boss_smi_die2_gpu_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "GPU"
    },
    {
     "expr": "boss_smi_die2_ddr_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "DDR"
    }
   ]
  },
  {
   "title": "Die3 Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boss_smi_die3_cpu_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "CPU"
    },
    {
     "expr": "boss_smi_die3_gpu_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "GPU"
    },
    {
     "expr": "boss_smi_die3_ddr_clock{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}*1000*1000",
     "legendFormat": "DDR"
    }
   ]
  },
  {
   "title": "Die3 Temperature",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_die3_bxlink_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "bxlink"
    },
    {
     "expr": "boss_smi_die3_gpgpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "gpgpu"
    },
    {
     "expr": "boss_smi_die3_cpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "cpu"
    },
    {
     "expr": "boss_smi_die3_ddr_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "ddr"
    },
    {
     "expr": "boss_smi_die3_decoder_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "decoder"
    },
    {
     "expr": "boss_smi_die3_sys_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "sys"
    }
   ]
  },
  {
   "title": "Die0 Limited Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boss_smi_die0_slowdown_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Slow Down"
    },
    {
     "expr": "boss_smi_die0_shutdown_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Shut Down"
    }
   ]
  },
  {
   "title": "Die1 Limited Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boss_smi_die1_slowdown_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Slow Down"
    },
    {
     "expr": "boss_smi_die1_shutdown_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Shut Down"
    }
   ]
  },
  {
   "title": "Die2 Limited Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boss_smi_die2_slowdown_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Slow Down"
    },
    {
     "expr": "boss_smi_die2_shutdown_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Shut Down"
    }
   ]
  },
  {
   "title": "Die3 Limited Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "boss_smi_die3_slowdown_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Slow Down"
    },
    {
     "expr": "boss_smi_die3_shutdown_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "Shut Down"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "timeseries",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "boss_smi_pwr{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Card Temperature",
   "type": "timeseries",
   "description": "inlet temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_inlet_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Inlet Temperature",
   "type": "timeseries",
   "description": "inlet temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_card_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Outlet Temperature",
   "type": "timeseries",
   "description": "Outlet temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_outlet_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die0 Information",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 25 },
   "options": { "content": "# Die0\n\n" },
   "targets": [
    { "expr": "boss_smi_die0_bxlink_temp{}", "legendFormat": "{{uuid}}" }
   ]
  },
  {
   "title": "Die1 Information",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 25 },
   "options": { "content": "# Die1\n\n" },
   "targets": [
    { "expr": "boss_smi_die0_bxlink_temp{}", "legendFormat": "{{uuid}}" }
   ]
  },
  {
   "title": "Die2 Information",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 12, "y": 25 },
   "options": { "content": "# Die2\n\n" },
   "targets": [
    { "expr": "boss_smi_die0_bxlink_temp{}", "legendFormat": "{{uuid}}" }
   ]
  },
  {
   "title": "Die3 Information",
   "type": "text",
   "gridPos": { "h": 1, "w": 6, "x": 18, "y": 25 },
   "options": { "content": "# Die3\n\n" },
   "targets": [
    { "expr": "boss_smi_die0_bxlink_temp{}", "legendFormat": "{{uuid}}" }
   ]
  },
  {
   "title": "Die0 CPU使用率",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "boss_smi_die0_cpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die1 CPU使用率",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "boss_smi_die1_cpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die2 CPU使用率",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "boss_smi_die2_cpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die3 CPU使用率",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "boss_smi_die3_cpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die0 GPU使用率",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "boss_smi_die0_gpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die1 GPU使用率",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "boss_smi_die1_gpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die2 GPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "boss_smi_die2_gpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die3 GPU使用率",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "boss_smi_die3_gpu_usage_rate{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die0 Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "boss_smi_die0_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Die1 Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "boss_smi_die1_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Die2 Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "boss_smi_die2_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Die3 Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "boss_smi_die3_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Die0 GPU Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "boss_smi_die0_gpu_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die1 GPU Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "boss_smi_die1_gpu_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die2 GPU Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "boss_smi_die2_gpu_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die3 GPU Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "boss_smi_die3_gpu_mem_used{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die0 BxLink Temperature",
   "type": "timeseries",
   "description": "Die0 BxLink temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die0_bxlink_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die1 BxLink Temperature",
   "type": "timeseries",
   "description": "Die1 BxLink temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die1_bxlink_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die2 BxLink Temperature",
   "type": "timeseries",
   "description": "Die2 BxLink temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die2_bxlink_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die3 BxLink Temperature",
   "type": "timeseries",
   "description": "Die3 BxLink temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die3_bxlink_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die0 GPGPU Temperature",
   "type": "timeseries",
   "description": "Die0 GPGPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die0_gpgpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die1 GPGPU Temperature",
   "type": "timeseries",
   "description": "Die1 GPGPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die1_gpgpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die2 GPGPU Temperature",
   "type": "timeseries",
   "description": "Die2 GPGPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die2_gpgpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die3 GPGPU Temperature",
   "type": "timeseries",
   "description": "Die3 GPGPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die3_gpgpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die0 CPU Temperature",
   "type": "timeseries",
   "description": "Die0 CPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die0_cpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die1 CPU Temperature",
   "type": "timeseries",
   "description": "Die1 CPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die1_cpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die2 CPU Temperature",
   "type": "timeseries",
   "description": "Die2 CPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die2_cpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die3 CPU Temperature",
   "type": "timeseries",
   "description": "Die3 CPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die3_cpu_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die0 DDR Temperature",
   "type": "timeseries",
   "description": "Die0 DDR temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die0_ddr_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die1 DDR Temperature",
   "type": "timeseries",
   "description": "Die1 DDR temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die1_ddr_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die2 DDR Temperature",
   "type": "timeseries",
   "description": "Die2 DDR temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die2_ddr_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die3 DDR Temperature",
   "type": "timeseries",
   "description": "Die3 DDR temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die3_ddr_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die0 Decoder Temperature",
   "type": "timeseries",
   "description": "Die0 Decoder temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die0_decoder_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die1 Decoder Temperature",
   "type": "timeseries",
   "description": "Die1 Decoder temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die1_decoder_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die2 Decoder Temperature",
   "type": "timeseries",
   "description": "Die2 Decoder temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die2_decoder_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die3 Decoder Temperature",
   "type": "timeseries",
   "description": "Die3 Decoder temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die3_decoder_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die0 sys Temperature",
   "type": "timeseries",
   "description": "Die0 sys temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die0_sys_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die1 sys Temperature",
   "type": "timeseries",
   "description": "Die1 sys temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die1_sys_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die2 sys Temperature",
   "type": "timeseries",
   "description": "Die2 sys temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die2_sys_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Die3 sys Temperature",
   "type": "timeseries",
   "description": "Die3 sys temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "boss_smi_die3_sys_temp{job=\"$this_job\", instance=\"$this_instance\", card_index=\"$this_cardid\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}