{
 "title": "boss APU Metrics",
 "description": "BlueOcean APU Metrics based on the prometheus metrics from github.com/dijiujun/boss_apu_exporter",
 "tags": [
  "boss",
  "boss-smi",
  "boss_apu_exporter",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "gpu",
    "label": "APU",
    "query": {
     "query": "label_values(boss_smi_index, uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Name",
   "type": "stat",
   "description": "The official product name of the APU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{uuid=\"$gpu\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "P-State",
   "type": "stat",
   "description": "The current performance state for the APU. States range from P0 (maximum performance) to P12 (minimum performance).",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "prefix:P" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_pstate{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "APU Utilization %",
   "type": "gauge",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the APU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_utilization_gpu_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Power Draw %",
   "type": "gauge",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts / The software power limit in watts.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_power_draw_watts{uuid=\"$gpu\"} / boss_smi_power_default_limit_watts{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "gauge",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_fan_speed_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Core APU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_temperature_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "graph",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "boss_smi_utilization_memory_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Driver Version",
   "type": "stat",
   "description": "The version of the installed BlueOcean BF400 driver. This is an alphanumeric string.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{uuid=\"$gpu\"}",
     "legendFormat": "{{driver_version}}"
    }
   ]
  },
  {
   "title": "Vbios Version",
   "type": "stat",
   "description": "The BIOS of the APU board.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_gpu_info{uuid=\"$gpu\"}",
     "legendFormat": "{{vbios_version}}"
    }
   ]
  },
  {
   "title": "Throttle Reasons",
   "type": "bargauge",
   "description": "Information about factors that are reducing the frequency of clocks. If all throttle reasons are returned as \"Not Active\" it means that clocks are running as high as possible.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_clocks_throttle_reasons_gpu_idle{uuid=\"$gpu\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "boss_smi_clocks_throttle_reasons_hw_thermal_slowdown{uuid=\"$gpu\"}",
     "legendFormat": "HW Thermal Slowdown"
    },
    {
     "expr": "boss_smi_clocks_throttle_reasons_sw_power_cap{uuid=\"$gpu\"}",
     "legendFormat": "SW Power Cap"
    },
    {
     "expr": "boss_smi_clocks_throttle_reasons_applications_clocks_setting{uuid=\"$gpu\"}",
     "legendFormat": "App Clocks Setting"
    },
    {
     "expr": "boss_smi_clocks_throttle_reasons_hw_power_brake_slowdown{uuid=\"$gpu\"}",
     "legendFormat": "HW Power Brake"
    },
    {
     "expr": "boss_smi_clocks_throttle_reasons_sw_thermal_slowdown{uuid=\"$gpu\"}",
     "legendFormat": "SW Thermal Slowdown"
    },
    {
     "expr": "boss_smi_clocks_throttle_reasons_sync_boost{uuid=\"$gpu\"}",
     "legendFormat": "Sync Boost"
    }
   ]
  },
  {
   "title": "APU Clock Speed %",
   "type": "gauge",
   "description": "Current frequency of graphics (shader) clock\n/\nMaximum frequency of graphics (shader) clock.\n",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_clocks_current_graphics_clock_hz{uuid=\"$gpu\"} / boss_smi_clocks_max_graphics_clock_hz{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Memory Clock Speed %",
   "type": "gauge",
   "description": "Current frequency of memory clock / Maximum frequency of memory clock",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_clocks_current_memory_clock_hz{uuid=\"$gpu\"} / boss_smi_clocks_max_memory_clock_hz{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Memory Allocation %",
   "type": "gauge",
   "description": "Total memory allocated by active contexts / Total installed APU memory.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_memory_used_bytes{uuid=\"$gpu\"} / boss_smi_memory_total_bytes{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "gauge",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "boss_smi_utilization_memory_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "APU Utilization %",
   "type": "graph",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the APU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "boss_smi_utilization_gpu_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "graph",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "boss_smi_memory_used_bytes{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "description": "Core APU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "boss_smi_temperature_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "graph",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "boss_smi_power_draw_watts{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "graph",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "boss_smi_fan_speed_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Graphics Clock Speed",
   "type": "graph",
   "description": "Current frequency of graphics (shader) clock.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "boss_smi_clocks_current_graphics_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Video Clock Speed",
   "type": "graph",
   "description": "Current frequency of video encoder/decoder clock.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "boss_smi_clocks_current_video_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "SM Clock Speed",
   "type": "graph",
   "description": "Current frequency of SM (Streaming Multiprocessor) clock.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "boss_smi_clocks_current_sm_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Clock Speed",
   "type": "graph",
   "description": "Current frequency of memory clock.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "boss_smi_clocks_current_memory_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}